"""Interactive scope.yaml creation — so nobody has to hand-edit YAML.

The rendering (`build_scope_yaml`) and target parsing (`normalize_targets`) are
pure and unit-tested; the interactive flow (`run_init`) takes injectable
ask/confirm/say callables so it can be driven by a script in tests with no TTY.
"""

from __future__ import annotations

import datetime as _dt
from typing import Callable
from urllib.parse import urlparse


def _dedupe(items: list[str]) -> list[str]:
    return list(dict.fromkeys(i for i in items if i))


def normalize_targets(entries: list[str]) -> tuple[list[str], list[str]]:
    """Turn typed targets into (hosts, url_prefixes).

    - A URL (``http://…``) is added as a URL prefix, and its host is allow-listed.
    - A bare host/IP is allow-listed, and a convenience ``http://<host>/`` prefix
      is added so you can point straight at it.
    """
    hosts: list[str] = []
    prefixes: list[str] = []
    for raw in entries:
        e = raw.strip()
        if not e:
            continue
        if e.startswith(("http://", "https://")):
            prefixes.append(e if e.endswith("/") else e + "/")
            host = urlparse(e).hostname
            if host:
                hosts.append(host)
        else:
            hosts.append(e)
            prefixes.append(f"http://{e}/")
    return _dedupe(hosts), _dedupe(prefixes)


def build_scope_yaml(
    *,
    operator: str,
    acknowledgement: str,
    signed: str,
    expires: str | None,
    hosts: list[str],
    url_prefixes: list[str],
    rate_limit_rps: float = 5,
    timeout_seconds: float = 15,
    user_agent: str = "PentARK/0.1 (authorized security testing)",
    audit_path: str = "pentark-audit.jsonl",
    authorized: bool = True,
) -> str:
    """Render a scope.yaml body. Pure (no I/O), for easy testing."""

    def _list(items: list[str]) -> str:
        if not items:
            return " []"
        return "\n" + "\n".join(f'    - "{i}"' for i in items)

    expires_line = f'  expires: "{expires}"\n' if expires else ""
    return (
        "# Generated by `pentark init`. Review before use.\n"
        "authorization:\n"
        f"  authorized: {'true' if authorized else 'false'}\n"
        f'  operator: "{operator}"\n'
        f'  acknowledgement: "{acknowledgement}"\n'
        f'  signed: "{signed}"\n'
        f"{expires_line}"
        "scope:\n"
        f"  hosts:{_list(hosts)}\n"
        f"  url_prefixes:{_list(url_prefixes)}\n"
        "settings:\n"
        f"  rate_limit_rps: {rate_limit_rps}\n"
        f"  timeout_seconds: {timeout_seconds}\n"
        f'  user_agent: "{user_agent}"\n'
        f'  audit_path: "{audit_path}"\n'
    )


_ACK = (
    "I have explicit written authorization to security-test the targets listed "
    "in this file, and I will stay within that authorization."
)


def run_init(
    ask: Callable[[str, str], str],
    confirm: Callable[[str], bool],
    say: Callable[[str], None],
    *,
    path,
    today: _dt.date | None = None,
    exists: bool | None = None,
) -> bool:
    """Interactively gather targets and write ``path``. Returns True if written."""
    from pathlib import Path

    path = Path(path)
    today = today or _dt.date.today()
    file_exists = path.exists() if exists is None else exists

    say("PentARK setup - this writes scope.yaml (your authorization allowlist).")
    if file_exists and not confirm(f"{path} already exists - overwrite it?"):
        say("Left the existing scope.yaml unchanged.")
        return False

    operator = ask("Your name and email (operator)", "Operator <you@example.com>")

    say("\nEnter each target you are AUTHORIZED to test - a host/IP (e.g. "
        "192.168.56.101) or a URL (e.g. http://localhost:3000/). Blank to finish.")
    entries: list[str] = []
    while True:
        t = ask("Target (blank to finish)", "")
        if not t.strip():
            break
        entries.append(t.strip())
    hosts, url_prefixes = normalize_targets(entries)
    if not hosts and not url_prefixes:
        say("\nNo targets entered - scope will be empty (default-deny; nothing runs).")

    default_expires = _dt.date(today.year, 12, 31).isoformat()
    expires = ask("Authorization expiry (YYYY-MM-DD)", default_expires)

    say("\nAuthorization attestation:")
    say(f'  "{_ACK}"')
    authorized = confirm("Do you attest the above for these targets?")
    if not authorized:
        say("Not attested - writing scope.yaml with authorized=false. Nothing active "
            "will run until you set it true yourself.")

    default_sign = operator.split("<")[0].strip() or operator
    signer = ask("Sign (your name)", default_sign)
    signed = f"{signer}, {today.isoformat()}"

    path.write_text(
        build_scope_yaml(
            operator=operator, acknowledgement=_ACK, signed=signed, expires=expires,
            hosts=hosts, url_prefixes=url_prefixes, authorized=authorized,
        ),
        encoding="utf-8",
    )
    say(f"\nWrote {path}." + ("" if authorized else " (authorized=false)"))
    return True


__all__ = ["normalize_targets", "build_scope_yaml", "run_init", "_ACK"]
